# Path to your oh-my-zsh configuration.
export ZSH=$HOME/.oh-my-zsh

# Set to the name theme to load.
# Look in ~/.oh-my-zsh/themes/
#export ZSH_THEME="macovsky"
export ZSH_THEME="minimal2"

# Set to this to use case-sensitive completion
# export CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# export DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# export DISABLE_LS_COLORS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(brew cloudapp git github git-flow lein vagrant zsh-syntax-highlighting)

export EDITOR=vim
export VISUAL=vim

source $ZSH/oh-my-zsh.sh
source ~/.zsh_local
source /usr/local/bin/virtualenvwrapper.sh

export VIRTUAL_ENV_DISABLE_PROMPT=1

export CLASSPATH=`cat ~/.clojure`

#export PROMPT='%{$fg[cyan]%}%m%{$reset_color%} %{$fg[green]%}%~%{$reset_color%} $(git_prompt_info)%{$reset_color%}%B$%b '

export PATH=~/bin:/usr/local/texlive/2011/bin/x86_64-darwin/:/usr/local/share/python:~/bin:/usr/local/Cellar/ruby/1.9.3-p125/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/X11/bin

. $HOME/Projects/z/z.sh
function precmd () {
  _z --add "$(pwd -P)"
}

alias va=vagrant
alias tx=tmux
alias ca=cloudapp

function wo () {
    workon $1
    cd $WORKON_HOME/$1
}

[[ -s $HOME/.rvm/scripts/rvm ]] && source $HOME/.rvm/scripts/rvm
